import { Router } from 'express'
import passport from 'passport'

import { localRegisterMiddleware, localLoginMiddleware } from './middleware'

const router = Router()

router.post('/register', localRegisterMiddleware, async (req, res) => {
  res.json({
    message: 'Registration successful',
    token: req.user, // 'user' is the object attached by passport.
    // In this case its the JWT generated by the local-register middleware.
  })
})

router.post('/login', localLoginMiddleware, async (req, res) => {
  res.json({
    message: 'Login successful',
    token: req.user,
  })
})

export default router
